= Roll Your Own Extension

The previous chapter introduced the major interfaces defined by Preon.
If you want to extend the framework, you just implement one of these interfaces.
Just the quickly recap the previous chapter, sorted by the relative relevance.
The CodecFactory is considered to be the most relevant interface, the BindingFactory is considered to be the least relevant. 

CodecFactory::
Implement this interface if you need to roll your own specific type of encoding.
Typically used when you want to add support for another datatype, or another compression scheme. 

CodecDecorator::
Implement this interface if you want to decorate the behaviour of a Codec that has already been constructed. 

BindingFactory::
Implement these interfaces if you want to change the way object fields and codecs are associated, to change the way the ObjectCodecFactory behaves. 

Given the interfaces above, let's see how you can extend the framework, starting with: 

== Adding support for a new datatype

Preon will _always_ try at least one strategy for decoding a field that has been marked with the @Bound annotation: if it fails to find decicated support for the datatype, then it will try to create a Codec using the ObjectCodecFactory.
This Codec will try to create a default instance of the datatype, and then try to populate its attributes, relying on the Preon annotations on those attributes. 

This may not be what you want.
There are many datatypes that have a more natural encoded representation.
Preon allows you to add support for this by implementing the CodecFactory. 

In this chapter, we are going to add support for Dates, relying on a very simple approach: we expect a Date to be encoded as the number of milisecons elapsed since the epoch.
And since it is encoded as a number, we will respect the @BoundNumber annotation. 